version: '3.7'

services:
  app:
    container_name: ${DOCKER_CONTAINER_PREFIX}.app
    command: npm run start:dev
    build:
      context: .
      target: builder
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres

  postgres:
    container_name: ${DOCKER_CONTAINER_PREFIX}.postgres
    image: postgres
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=vincelivemix
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB}:${POSTGRES_DB}

volumes:
  node_modules:
