version: '3.7'

services:
  app:
    container_name: ${DOCKER_CONTAINER_PREFIX}.app
    command: sh -c "/usr/local/bin/wait && npm run start:dev"
    build:
      context: docker
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:cached
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  postgres:
    container_name: ${DOCKER_CONTAINER_PREFIX}.postgres
    image: postgres:12.7
    volumes:
      - postgres_vincelivemix:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_vincelivemix: {}
