version: '3.7'

services:
  app:
    container_name: ${DOCKER_CONTAINER_PREFIX}.app
    command: sh -c "/usr/local/bin/wait && npm run start:dev"
    build:
      context: docker
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:cached
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - postgres
    environment:
      - WAIT_HOSTS=postgres:5432
      - DATABASE_URL=${DATABASE_URL}

  postgres:
    container_name: ${DOCKER_CONTAINER_PREFIX}.postgres
    image: postgres:14.8
    volumes:
      - postgres_vincelivemix:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vincelivemix

volumes:
  postgres_vincelivemix: {}
