version: '3.7'

services:
  app:
    container_name: ${DOCKER_CONTAINER_PREFIX}.app
    command: sh -c "/usr/local/bin/wait && npm run start:dev"
    build:
      context: docker
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS=postgres:5432
      - TYPEORM_HOST=postgres
    volumes:
      - .:/app:cached
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: ${DOCKER_CONTAINER_PREFIX}.postgres
    image: postgres:11
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=vincelivemix
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
