version: '3.7'

services:
  app:
    container_name: ${DOCKER_CONTAINER_PREFIX}.app
    command: sh -c "/usr/local/bin/wait && npm run start:dev"
    build:
      context: docker
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:cached
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - postgres

  postgres:
    container_name: ${DOCKER_CONTAINER_PREFIX}.postgres
    image: postgres:12.2
    volumes:
      - postgres_vincelivemix:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  postgres_vincelivemix: {}
