# Dockerfile for development only
FROM node:21.7.3
WORKDIR /app

## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.6.0/wait /usr/local/bin/wait
RUN chmod +x /usr/local/bin/wait
